// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import { primeReactThemes } from '../theme';

describe('when checking the token vocabulary', () => {
    const vocabulary = [
        'primary.color',
        'primary.contrastColor',
        'surface.background',
        'surface.card',
        'surface.border',
        'surface.hover',
        'surface.overlay',
        'text.color',
        'text.mutedColor',
        'highlight.background',
        'highlight.color',
        'content.borderRadius',
        'focus.ring',
    ];

    it('should give every theme the whole vocabulary', () => {
        const incomplete = primeReactThemes
            .filter((theme) => vocabulary.some((token) => theme.tokens?.[token] === undefined))
            .map((theme) => theme.name);
        incomplete.should.deep.equal([]);
    });

    it('should give every theme nothing but the vocabulary, so packages can agree on it', () => {
        const extra = primeReactThemes.flatMap((theme) => Object.keys(theme.tokens ?? {}).filter((token) => !vocabulary.includes(token)));
        extra.should.deep.equal([]);
    });

    it('should say whether every theme is dark', () => {
        primeReactThemes.filter((theme) => theme.isDark === undefined).should.deep.equal([]);
    });

    it('should ship both light and dark themes', () => {
        primeReactThemes.some((theme) => theme.isDark === true).should.be.true;
        primeReactThemes.some((theme) => theme.isDark === false).should.be.true;
    });

    /**
     * The token values are generated by resolving each preset's `{path}` references and `light-dark()`
     * pairs, so the risk is not a typo but a resolver that silently gave up - leaving a raw `{emerald.500}`
     * or an unpicked `light-dark(...)` in the catalog, which reaches CSS as a value the browser drops.
     */
    it('should have resolved every token to a literal value rather than leaving a preset reference behind', () => {
        const unresolved = primeReactThemes.flatMap((theme) =>
            Object.entries(theme.tokens ?? {})
                .filter(([, value]) => value.includes('{') || value.includes('light-dark('))
                .map(([token]) => `${theme.name}: ${token}`)
        );
        unresolved.should.deep.equal([]);
    });

    it('should mirror the accent the preset binds for a light theme', () => {
        primeReactThemes.find((theme) => theme.name === 'lara-light-blue')!.tokens!['primary.color'].should.equal('#3b82f6');
    });

    /**
     * A dark theme takes the lighter step of the accent ramp, not the same value as its light sibling.
     * Getting this wrong is the classic `light-dark()` resolution bug and produces a dark theme that is
     * legible everywhere except its own accent.
     */
    it('should take the accent from the lighter end of the ramp for a dark theme', () => {
        primeReactThemes.find((theme) => theme.name === 'lara-dark-blue')!.tokens!['primary.color'].should.equal('#60a5fa');
    });
});
