<Project>
    <PropertyGroup>
        <ImplicitUsings>true</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>

        <!-- Debuggability -->
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <IncludeSource>True</IncludeSource>
        <!-- Debuggability - End -->

        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
        <RunAnalyzers>True</RunAnalyzers>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>

        <NoWarn>NU1507;NU1608;NU1510;NU1603;NU1605;CS1705;IDE0031;IDE0032;IDE0340;CA1873;IDE0330;MA0158;MA0190;ASPDEPR002;CS8602;CS8604;CS8670;RCS1238;SA1414;CA1034</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'==''">
        <Configuration>Debug</Configuration>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release' AND '$(TargetFramework)'=='' AND '$(TargetFrameworks)'==''">
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug' AND '$(TargetFramework)'=='' AND '$(TargetFrameworks)'==''">
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
        <PackageReference Include="Roslynator.Analyzers" PrivateAssets="All" />
        <PackageReference Include="Meziantou.Analyzer" PrivateAssets="All" />
    </ItemGroup>
</Project>
