// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import { Theme } from '@cratis/scene.model';
import { PrimeReactThemeFamily } from './PrimeReactThemeFamily';

/**
 * One PrimeReact theme, minus everything that is identical for all of them, plus the two facts a v11
 * theme needs that a v10 theme did not: which `@primeuix/themes` preset family it is built on, and which
 * primitive color ramp is bound to the preset's primary scale.
 *
 * Attribution and compatibility are deliberately *not* here: they are added once, for every preset, in
 * `primeReactThemes`. Every one of these themes is PrimeTek's design work and none of them is ours, so
 * crediting them one entry at a time would make it possible to add a twenty-fifth and forget - and a
 * dropped credit is not the kind of mistake a code review reliably catches.
 */
export type ThemePreset = Omit<Theme, 'compatibleWith' | 'author' | 'authorUrl' | 'license'> & {
    /**
     * The `@primeuix/themes` preset family this theme applies through `PrimeReactProvider`.
     */
    family: PrimeReactThemeFamily;

    /**
     * The name of the primitive color ramp bound to the preset's `primary` scale - the accent the whole
     * theme is tinted by.
     */
    primaryColor: string;
};

/**
 * Every theme this package ships, and the Scene tokens each one stands for.
 *
 * This is data, not logic, but unlike the PrimeReact 10 catalog it is *derived* data. A v10 theme was a
 * compiled stylesheet whose `:root` block could be read with a text editor, so the token values were
 * transcribed by hand. A v11 theme is a JavaScript preset whose values are token *references* -
 * `{emerald.500}`, `light-dark({surface.0}, {surface.900})` - resolved by `@primeuix/styled` at runtime.
 * Transcribing those by hand would mean re-implementing the resolver in one's head, once per theme.
 *
 * So these values were generated: each preset was loaded, its `primary` scale bound to the chosen color
 * ramp, and the thirteen Scene tokens resolved through the same `light-dark()` and `{path}` rules
 * `@primeuix/styled` applies. What is committed here is the *output* of that resolution, so the catalog
 * stays plain data that a theme picker can read without booting a theme engine - while still agreeing,
 * value for value, with what the preset actually renders.
 *
 * The catalog is not a like-for-like port of the v10 one. PrimeReact 11 ships four preset families -
 * Aura, Lara, Nora and Material - and the v10 themes that had no counterpart among them (`saga`,
 * `vela`, `arya`, `bootstrap4`, `soho`, `viva`, `nano`, `mira`, `fluent-light`, `tailwind-light`) are
 * not carried over. Renaming a Lara onto `soho-dark` would have kept the catalog's length at the cost
 * of its honesty.
 */
export const themePresets: ThemePreset[] = [
    {
        name: 'aura-light-blue',
        description: 'Aura, the flagship PrimeReact 11 design language, in light on a blue accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'blue',
        isDark: false,
        tokens: {
            'primary.color': '#3b82f6',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#eff6ff',
            'highlight.color': '#1d4ed8',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-dark-blue',
        description: 'Aura, the flagship PrimeReact 11 design language, in dark on a blue accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'blue',
        isDark: true,
        tokens: {
            'primary.color': '#60a5fa',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #60a5fa, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-light-indigo',
        description: 'Aura, the flagship PrimeReact 11 design language, in light on an indigo accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'indigo',
        isDark: false,
        tokens: {
            'primary.color': '#6366f1',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#eef2ff',
            'highlight.color': '#4338ca',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-dark-indigo',
        description: 'Aura, the flagship PrimeReact 11 design language, in dark on an indigo accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'indigo',
        isDark: true,
        tokens: {
            'primary.color': '#818cf8',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #818cf8, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-light-purple',
        description: 'Aura, the flagship PrimeReact 11 design language, in light on a purple accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'purple',
        isDark: false,
        tokens: {
            'primary.color': '#a855f7',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#faf5ff',
            'highlight.color': '#7e22ce',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-dark-purple',
        description: 'Aura, the flagship PrimeReact 11 design language, in dark on a purple accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'purple',
        isDark: true,
        tokens: {
            'primary.color': '#c084fc',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #c084fc, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-light-teal',
        description: 'Aura, the flagship PrimeReact 11 design language, in light on a teal accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'teal',
        isDark: false,
        tokens: {
            'primary.color': '#14b8a6',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#f0fdfa',
            'highlight.color': '#0f766e',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'aura-dark-teal',
        description: 'Aura, the flagship PrimeReact 11 design language, in dark on a teal accent.',
        family: PrimeReactThemeFamily.Aura,
        primaryColor: 'teal',
        isDark: true,
        tokens: {
            'primary.color': '#2dd4bf',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #2dd4bf, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'lara-light-blue',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in light on a blue accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'blue',
        isDark: false,
        tokens: {
            'primary.color': '#3b82f6',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#eff6ff',
            'highlight.color': '#1d4ed8',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem #bfdbfe',
        },
    },
    {
        name: 'lara-dark-blue',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in dark on a blue accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'blue',
        isDark: true,
        tokens: {
            'primary.color': '#60a5fa',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #60a5fa, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem color-mix(in srgb, #60a5fa, transparent 80%)',
        },
    },
    {
        name: 'lara-light-indigo',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in light on an indigo accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'indigo',
        isDark: false,
        tokens: {
            'primary.color': '#6366f1',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#eef2ff',
            'highlight.color': '#4338ca',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem #c7d2fe',
        },
    },
    {
        name: 'lara-dark-indigo',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in dark on an indigo accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'indigo',
        isDark: true,
        tokens: {
            'primary.color': '#818cf8',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #818cf8, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem color-mix(in srgb, #818cf8, transparent 80%)',
        },
    },
    {
        name: 'lara-light-purple',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in light on a purple accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'purple',
        isDark: false,
        tokens: {
            'primary.color': '#a855f7',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#faf5ff',
            'highlight.color': '#7e22ce',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem #e9d5ff',
        },
    },
    {
        name: 'lara-dark-purple',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in dark on a purple accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'purple',
        isDark: true,
        tokens: {
            'primary.color': '#c084fc',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #c084fc, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem color-mix(in srgb, #c084fc, transparent 80%)',
        },
    },
    {
        name: 'lara-light-teal',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in light on a teal accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'teal',
        isDark: false,
        tokens: {
            'primary.color': '#14b8a6',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#e2e8f0',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#334155',
            'text.mutedColor': '#64748b',
            'highlight.background': '#f0fdfa',
            'highlight.color': '#0f766e',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem #99f6e4',
        },
    },
    {
        name: 'lara-dark-teal',
        description: 'Lara, the roomy family Scene shipped on PrimeReact 10, in dark on a teal accent.',
        family: PrimeReactThemeFamily.Lara,
        primaryColor: 'teal',
        isDark: true,
        tokens: {
            'primary.color': '#2dd4bf',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #2dd4bf, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '6px',
            'focus.ring': '0 0 0 0.2rem color-mix(in srgb, #2dd4bf, transparent 80%)',
        },
    },
    {
        name: 'nora-light-blue',
        description: 'Nora, a tighter, squarer, more compact family, in light on a blue accent.',
        family: PrimeReactThemeFamily.Nora,
        primaryColor: 'blue',
        isDark: false,
        tokens: {
            'primary.color': '#2563eb',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#94a3b8',
            'surface.hover': '#e2e8f0',
            'surface.overlay': '#ffffff',
            'text.color': '#0f172a',
            'text.mutedColor': '#475569',
            'highlight.background': '#2563eb',
            'highlight.color': '#ffffff',
            'content.borderRadius': '2px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'nora-dark-blue',
        description: 'Nora, a tighter, squarer, more compact family, in dark on a blue accent.',
        family: PrimeReactThemeFamily.Nora,
        primaryColor: 'blue',
        isDark: true,
        tokens: {
            'primary.color': '#3b82f6',
            'primary.contrastColor': '#09090b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#71717a',
            'surface.hover': '#3f3f46',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': '#3b82f6',
            'highlight.color': '#09090b',
            'content.borderRadius': '2px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'nora-light-indigo',
        description: 'Nora, a tighter, squarer, more compact family, in light on an indigo accent.',
        family: PrimeReactThemeFamily.Nora,
        primaryColor: 'indigo',
        isDark: false,
        tokens: {
            'primary.color': '#4f46e5',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#94a3b8',
            'surface.hover': '#e2e8f0',
            'surface.overlay': '#ffffff',
            'text.color': '#0f172a',
            'text.mutedColor': '#475569',
            'highlight.background': '#4f46e5',
            'highlight.color': '#ffffff',
            'content.borderRadius': '2px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'nora-dark-indigo',
        description: 'Nora, a tighter, squarer, more compact family, in dark on an indigo accent.',
        family: PrimeReactThemeFamily.Nora,
        primaryColor: 'indigo',
        isDark: true,
        tokens: {
            'primary.color': '#6366f1',
            'primary.contrastColor': '#09090b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#71717a',
            'surface.hover': '#3f3f46',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': '#6366f1',
            'highlight.color': '#09090b',
            'content.borderRadius': '2px',
            'focus.ring': 'none',
        },
    },
    {
        name: 'material-light-indigo',
        description: 'Material, the PrimeTek reading of Material Design, in light on an indigo accent.',
        family: PrimeReactThemeFamily.Material,
        primaryColor: 'indigo',
        isDark: false,
        tokens: {
            'primary.color': '#3F51B5',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#cbd5e1',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#0f172a',
            'text.mutedColor': '#475569',
            'highlight.background': 'color-mix(in srgb, #3F51B5, transparent 88%)',
            'highlight.color': '#303F9F',
            'content.borderRadius': '4px',
            'focus.ring': '0 0 1px 4px #e2e8f0',
        },
    },
    {
        name: 'material-dark-indigo',
        description: 'Material, the PrimeTek reading of Material Design, in dark on an indigo accent.',
        family: PrimeReactThemeFamily.Material,
        primaryColor: 'indigo',
        isDark: true,
        tokens: {
            'primary.color': '#5C6BC0',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #5C6BC0, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '4px',
            'focus.ring': '0 0 1px 4px #3f3f46',
        },
    },
    {
        name: 'material-light-purple',
        description: 'Material, the PrimeTek reading of Material Design, in light on a purple accent.',
        family: PrimeReactThemeFamily.Material,
        primaryColor: 'purple',
        isDark: false,
        tokens: {
            'primary.color': '#9C27B0',
            'primary.contrastColor': '#ffffff',
            'surface.background': '#f8fafc',
            'surface.card': '#ffffff',
            'surface.border': '#cbd5e1',
            'surface.hover': '#f1f5f9',
            'surface.overlay': '#ffffff',
            'text.color': '#0f172a',
            'text.mutedColor': '#475569',
            'highlight.background': 'color-mix(in srgb, #9C27B0, transparent 88%)',
            'highlight.color': '#7B1FA2',
            'content.borderRadius': '4px',
            'focus.ring': '0 0 1px 4px #e2e8f0',
        },
    },
    {
        name: 'material-dark-purple',
        description: 'Material, the PrimeTek reading of Material Design, in dark on a purple accent.',
        family: PrimeReactThemeFamily.Material,
        primaryColor: 'purple',
        isDark: true,
        tokens: {
            'primary.color': '#AB47BC',
            'primary.contrastColor': '#18181b',
            'surface.background': '#09090b',
            'surface.card': '#18181b',
            'surface.border': '#3f3f46',
            'surface.hover': '#27272a',
            'surface.overlay': '#18181b',
            'text.color': '#ffffff',
            'text.mutedColor': '#a1a1aa',
            'highlight.background': 'color-mix(in srgb, #AB47BC, transparent 84%)',
            'highlight.color': 'rgba(255,255,255,.87)',
            'content.borderRadius': '4px',
            'focus.ring': '0 0 1px 4px #3f3f46',
        },
    },
];
